//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorTxtPedidosYa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HiperOleEntities : DbContext
    {
        public HiperOleEntities()
            : base("name=Entities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 32000;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sucursales_Activas> Sucursales_Activas { get; set; }
    
        [EdmFunction("Entities", "Reporte_PedidosYa")]
        public virtual IQueryable<Reporte_PedidosYa_Result> Reporte_PedidosYa(string sUCURSAL, string cODIGOS)
        {
            var sUCURSALParameter = sUCURSAL != null ?
                new ObjectParameter("SUCURSAL", sUCURSAL) :
                new ObjectParameter("SUCURSAL", typeof(string));
    
            var cODIGOSParameter = cODIGOS != null ?
                new ObjectParameter("CODIGOS", cODIGOS) :
                new ObjectParameter("CODIGOS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Reporte_PedidosYa_Result>("[Entities].[Reporte_PedidosYa](@SUCURSAL, @CODIGOS)", sUCURSALParameter, cODIGOSParameter);
        }
    }
}
