//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorTxtPedidosYa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales_Activas
    {
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string EMPRESA { get; set; }
        public string PEDIDOSYA { get; set; }
    }
}
